version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - './backend:/app'
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - '5000:5000'
  frontend:
    build: ./frontend
    volumes:
      - './frontend/:/app'
    ports:
      - '3000:3000'
  mobile:
    build: ./mobile
    volumes:
      - './mobile:/app'
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'