version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ml_celebrity_match'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./.data:/var/lib/mysql
  backend:
    build: ./backend
    volumes:
      - './backend:/app'
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - '5000:5000'
  frontend:
    build: ./frontend
    volumes:
      - './frontend/:/app'
    ports:
      - '3000:3000'
