version: '3'

services:
  backend:
    build: ../celebrity-match-backend
    volumes:
      - '../celebrity-match-backend:/app'
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - '5000:5000'
  frontend:
    build: .
    volumes:
      - './:/app'
    ports:
      - '3000:3000'